### ISSUE TITLE
These are not private :0

### ISSUE THREAD

**Issue by a-swedish-developer** [helagro/private_notes#1]
![image](https://user-images.githubusercontent.com/31438039/173579400-a5b4df49-3dd4-4fb2-9f90-ef0d832a15c0.png)

**Comment by a-swedish-developer** [comment]
Or maybe I misunderstood, it's an app to write private notes, it's not the repo that's meant to be private... I guess.

**Comment by helagro** [comment]
That is correct. Thx for warning though!
